### ISSUE TITLE
Suggestion: add a black type

### ISSUE THREAD

**Issue by zhaoyao91** [Cogoport/cogo-toast#31]
see https://material.io/components/snackbars/#

sometimes we may popup some toast to **sligtly** give user some info, but not trying to catch too much attention.

**Comment by anmolmahatpurkar** [comment]
@zhaoyao91 Hey, this can be done by extending the CSS. You can change the styles of the toast by modifying the `ct-toast` class in the css file of your project.

```css
.ct-toast {
  background: #333;
  color: #fff;
}
```
